In [29]:
# Step 1
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

In [30]:
# Step 2 (Task 1)
# Part A — Print the shape of the data :-
print("Shape of data:", data.shape)

# Part B — Compute mean temperature per station :-
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:", mean_per_station)

Shape of data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]


In [31]:
# Step 3 (Task 2)
# Now create a boolean mask for values above 28.0 :-
mask = data > 28.0

# Apply mask and flatten to 1D array :-
high_temps = data[mask]
print("Temperatures above 28°C:", high_temps)

Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [32]:
# Step 4 (Task 3)
# Now Normalize data into [0, 1] form :-
normalized = (data - data.min()) / (data.max() - data.min())

# Round to 2 decimal places
normalized = np.round(normalized, 2)

print("Normalized data:\n", normalized)

Normalized data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]


# Explanation :-
➡  **data.min() is the smallest temperature in the whole array.**

➡  **data.max() is the largest.**

➡  **Formula converts all numbers into a scale between 0 (min) and 1 (max).**

➡  **np.round(normalized, 2) keeps only 2 decimal places.**